### ISSUE TITLE
High level conceptual introduction of approximate (fuzzy) vs probabilistic

### ISSUE THREAD

**Issue by RobinL** [mshearer0/HandsOnEntityResolution#28]
Not sure where this fits, but I think it would be useful to have some text that tries to describe the conceptual difference between fuzzy matching and probabilistic.

Here's some text I wrote on our slack channel at one point that tries to describe the distinction, any why fuzzy matching (whilst good) misses a lot of relevant information.  You're welcome to use any of these ideas and parts or all of this description if you think it's useful

when performing record linkage there are (broadly) three sources of information, of which fuzzy matching functions like levenstein/jaro etc. are just one:

1. Fuzzy matching functions that can detect the similarity between strings, but are unaware of the larger context of the dataset.  So ‘Pepsi’ and Pepsu’ have a jaro winkler score of 0.92.  But so do ‘Group’ and ‘Grouo’
2. An understanding of the cardinality of the field (number of distinct values), and the likelihood of coincidences occuring.  An exact match on the token ‘Pepsi’ provides much stronger evidence in favour of a match than a match on ‘Group’.  Similarly a fuzzy match on Pepsi at 0.92 is much stronger evidence of a match than a fuzzy match on Group.  The relevant question  is ’how much of a coincidence would it be to observed to different companies with a 0.92 match of ‘Group’ and ‘Grouo’ - and probabilistic models properly quantify this.
3. The strength of evidence against two record matching when fields do not match.  For example, if you observe ‘Pepsi Ltd’ vs ‘Pepsi PLC’, how much negative weight should we assign to the mismatch (Ltd vs PNC)  - how much evidence is this against these two records matching.

A lot of the power of probabilistic models comes from properly combining all three sources of information.  For large scale record linkage, it turns out that (2) and (3) are usually more powerful sources of accuracy that (1), particularly in the case you have multiple columns in your input dataset (e.g. if you have things in addition to the name, such as company address, directors names, turnover, legal structure, or anything else).

**Comment by mshearer0** [comment]
Thanks Robin - I've revised Chapter 4 to draw this out a bit more
