### ISSUE TITLE
When training models, use `linker.estimate_probability_two_random_records_match`, or estimate u during EM 

### ISSUE THREAD

**Issue by RobinL** [mshearer0/HandsOnEntityResolution#39]
When you're training models, it's important to estimate  the prior  (sometimes called lambda,  or in Splink `probability_two_random_records_match`) as accurately as possible.

This will improve the stability of EM and make the threshold match probability you use in `predict()` more intuitive/accurate.

You can see it being estimated here using a direct estimation technique which we believe to be best practice:
https://moj-analytical-services.github.io/splink/demos/04_Estimating_model_parameters.html#estimation-of-probability_two_random_records_match

Or, you can use `linker.estimate_parameters_using_expectation_maximisation`, but set the `fix_u_probabilities` to False
[here](https://github.com/moj-analytical-services/splink/blob/71b89368c094906f22f20f3369c91b7fb25f7b4e/splink/linker.py#L1485).  However, that can sometimes give bad results when the input columns are correlated.

An example of where this is needed is page 73 - in that model you're not training `probability_two_random_records_match` at all I don't think give then current code/settings

**Comment by mshearer0** [comment]
Thanks Robin. I've added fix_u_probabilities = False as in Chapter 4
